### ISSUE TITLE
How would you use it with S3?

### ISSUE THREAD

**Issue by PolGuixe** [voodooattack/file-scalar#1]
I am new to GraphQL, so I am still trying to get my head around it. I would like to use vulcan: forms-update with S3. 

Would you use the [meteor-files](https://github.com/VeliovGroup/Meteor-Files) package or the  [aws-sdk](https://www.npmjs.com/package/aws-sdk) package straigh-away?

**Comment by voodooattack** [comment]
I’d use CollectionFS. It already supports S3: https://github.com/CollectionFS/Meteor-CollectionFS

**Comment by PolGuixe** [comment]
CollectionFS seems that it is not seeing much maintenance. Meteor-Files is actively maintained, will it be possible to use it with file-scalar?

**Comment by voodooattack** [comment]
It should be usable, instead of calling `addFile()`, you should use `write()` with the stream object like so:

```js
const Images = new FilesCollection({collectionName: 'Images'});

const newFile = Images.write(stream, {
  fileName: stream.filename,
  type: stream.mimeType,
});
 
```

**Comment by PolGuixe** [comment]
@voodooattack I've tried to implement it, however, I am getting an error. I've started an issue here:
https://github.com/VeliovGroup/Meteor-Files/issues/562

**Comment by voodooattack** [comment]
I see you've found a solution. Should I close this too?
