### ISSUE TITLE
GraphQL Bad Getaway 502

### ISSUE THREAD

**Issue by PolGuixe** [voodooattack/file-scalar#2]
I managed to make it work on local. However once deployed to server I am getting a POST error on GraphQL indicating bad getaway error 502. 

Did you have a similar experience once deployed?

**Comment by voodooattack** [comment]
Hi! Thanks for the bug report!

And the answer is no, this issue has never come up before. Can you provide any extra details, like the specifics of your setup or request logs?

**Comment by PolGuixe** [comment]
The problem is related with Apollo Engine. Without Apollo Engine it worked fine. I'll have to check with the new updates they are doing to Apollo as this is from 2-3 months ago. 

Finally, we ended up creating a package for file management for Vulcan: https://github.com/OrigenStudio/vulcan-files

**Comment by voodooattack** [comment]
@PolGuixe I see, thanks. I'm closing this then.
